---

- hosts: db
  sudo: yes
  tasks:
   - name: Install MariaDB Packages
     yum: name=mariadb-server state=present

   - name: Start MariaDB Service
     service: name=mariadb state=started

- hosts: datacenter
  sudo: yes
  tasks:
  - name: Stop the firwall
    service: name=firewalld state=stopped enabled=False
